language: java

addons:
    apt:
        packages:
        - texlive-xetex
        - texlive-latex-recommended
        - texlive-latex-extra
        - texlive-fonts-extra
        - texlive-formats-extra
        - texlive-extra-utils
        - texlive-generic-extra
        - weka

script:
    - ant test
    - ant weka-package
    - java -cp /usr/share/java/weka.jar weka.core.WekaPackageManager -install-package autoweka.zip
