language: java

addons:
    apt:
        packages:
        - texlive-xetex
        - texlive-latex-recommended
        - texlive-latex-extra
        - texlive-fonts-extra
        - texlive-formats-extra
        - texlive-extra-utils
        - texlive-generic-extra
        - weka

script:
    - ant test
    - ant weka-package
    - java -cp lib/weka.jar weka.core.WekaPackageManager -install-package autoweka.zip
    - java -cp build/jar/autoweka.jar weka.classifiers.meta.AutoWEKAClassifier -t /tmp/iris.arff -no-cv -timeLimit 15
